### PR TITLE
Added Sparse to Compact Matrix Calculator

### LINKED ISSUE #503: Adding Sparse to Compact Matrix Converter
# Description

## Please assign me this issue under JWOC 2023. @Srijita-Mandal

### PR DESCRIPTION
**Pull request by pooranjoyb**
## This PR adds Sparse to Compact Matrix to the Calculator and closes #503 

Would be glad if you'd merge this PR @Srijita-Mandal

### CODE REVIEW

**Comment by pooranjoyb** [comment]
Hey @Srijita-Mandal Could you please revise the difficulty level of this PR? I thought it to be medium, but it was really difficult to serve the result in the DOM.

**Comment by Srijita-Mandal** [comment]
> Hey @Srijita-Mandal Could you please revise the difficulty level of this PR? I thought it to be medium, but it was really difficult to serve the result in the DOM.

Yeah. Do one thing. Remove the all default `0` values from matrix input. `0` could be placeholder or could be blank.

**Comment by pooranjoyb** [comment]
Okay, will do that for sure. Meanwhile change the difficulty level. @Srijita-Mandal

**Comment by Srijita-Mandal** [comment]
> Okay, will do that for sure. Meanwhile change the difficulty level. @Srijita-Mandal

Make this commit with your next PR.

**Pull request merged**
