### PR TITLE
Retirement calculator updated

### PR DESCRIPTION
**Pull request by Priyamakeshwari**
I have updated please check it 
image

### CODE REVIEW

**Comment by Priyamakeshwari** [comment]
You are merging others pull request without merging mine so again and again I am getting conflicts
I created the PR on march 1st  by resolving the conflicts , I didnt face any issue but now when i checked again on github I am facing the same merge conflicts. @Srijita-Mandal

**Comment by Priyamakeshwari** [comment]
I have updated it again please kindly merge it .

**Comment by Srijita-Mandal** [comment]
@Priyamakeshwari I would manage your conflicts and resolve this. But you have deleted some other codes. Anyway, merged it.

**Comment by Priyamakeshwari** [comment]
okay thanks.

**Pull request merged**
