### PR TITLE
About Us page added

### PR DESCRIPTION
**Pull request by Saishreekouda**
image

Screenshot 2023-03-04 at 3 42 08 PM
image

### CODE REVIEW

**Comment by Srijita-Mandal** [comment]
In the issue #209 I mentioned to add the list of calculators. You haven't do that.

**Comment by Saishreekouda** [comment]
Oh, I didnt see that, I will make the changes

**Comment by Saishreekouda** [comment]
@Srijita-Mandal should i add the same section that is there on the home page or should it just be a list with no description?

**Comment by Srijita-Mandal** [comment]
> @Srijita-Mandal should i add the same section that is there on the home page or should it just be a list with no description?

Just list the names of calculators, no descriptions needed, with some styling.

**Pull request closed without merging**
