### PR TITLE
Added Timezone

### PR DESCRIPTION
**Pull request by Viveksati5143**
Closes: #571 @S-ishita

### CODE REVIEW

**Comment by Srijita-Mandal** [comment]
@Viveksati5143 Attach screenshots or screen recording or deployed link from your branch.

**Comment by Viveksati5143** [comment]
image
Done @Srijita-Mandal

**Comment by Viveksati5143** [comment]
image
Done @Srijita-Mandal

**Comment by Viveksati5143** [comment]
Please merge it now ASAP @Srijita-Mandal  so i can work on other issues

**Comment by Viveksati5143** [comment]
@Srijita-Mandal ???

**Pull request merged**
