### PR TITLE
Added LCA calculator

### PR DESCRIPTION
**Pull request by Saishreekouda**
Screenshot 2023-03-16 at 6 24 58 PM

### CODE REVIEW

**Comment by Srijita-Mandal** [comment]
@Saishreekouda The dark mode is not working. fix it.

**Comment by Saishreekouda** [comment]
Done.

**Comment by Srijita-Mandal** [comment]
> Done.

Have you push your commit?

**Comment by Saishreekouda** [comment]
Yes, https://saishreekouda.github.io/fix-your-nums/html_files/lca.html

**Comment by Srijita-Mandal** [comment]
Please make a PR with the new commit. This could be a hard labeled issue.

**Pull request merged**
