### PR TITLE
profitLoss calculator

### PR DESCRIPTION
**Pull request by Laxmankohar**
Fixes: issue no #214 

image
image
image

### CODE REVIEW

**Comment by Laxmankohar** [comment]
please add the label.

**Comment by Srijita-Mandal** [comment]
@Laxmankohar you haven't add this calculator to the home page. Please complete that.

**Comment by Laxmankohar** [comment]
Should i have to make new Pull request?

**Comment by Srijita-Mandal** [comment]
Added the tags to the new PR,

**Pull request merged**
