### PR TITLE
Number to word converter is added

### PR DESCRIPTION
**Pull request by LuckySingh9897**
Issue #134-- num-to-word converter is added.

### CODE REVIEW

**Comment by Srijita-Mandal** [comment]
@LuckySingh9897 Please attach some screenshots or screen recording or any link of how you implemented that.

**Comment by LuckySingh9897** [comment]
Screenshot_20230224_185845
Screenshot_20230224_185902
Screenshot_20230224_185915

these are the screenshots of the calculator step by step @Srijita-Mandal

**Comment by Srijita-Mandal** [comment]
Here your have added 3 new files. Didn't you add this calculator to home page?

**Comment by LuckySingh9897** [comment]
@Srijita-Mandal  I have linked it to the home page please check.

**Pull request merged**
