### PR TITLE
Added Retirement saving calculator

### LINKED ISSUE #612: Retirement savings calculator
A Retirement Savings Calculator is a tool that helps individuals estimate how much they should save each month to achieve their retirement goals. It takes into account factors such as the individual's current age, desired retirement age, expected retirement income, expected expenses in retirement, and the expected rate of return on investments.

### PR DESCRIPTION
**Pull request by Viveksati5143**
Closes: #612 @Srijita-Mandal 
225717329-5179a5a0-c58b-41e4-bc8c-3d6f3a00c666

### CODE REVIEW

**Comment by Viveksati5143** [comment]
@Srijita-Mandal

**Comment by Srijita-Mandal** [comment]
> @Srijita-Mandal???

@Viveksati5143 PRs after 11.59pm of 16th are not counted.

**Comment by Viveksati5143** [comment]
@Srijita-Mandal check issue #628 Check the time it was before time. But then you created merge conflicts remember?

**Comment by Viveksati5143** [comment]
@Srijita-Mandal Let it be fair.

**Comment by Viveksati5143** [comment]
@Srijita-Mandal add jwoc label??

**Comment by Srijita-Mandal** [comment]
> @Srijita-Mandal add jwoc label??

Labels of this PR won't be calculated as the PR date is 17th. Labels are added to PR #628

**Comment by Viveksati5143** [comment]
But it the same pr right no code or anything is changed? @Srijita-Mandal

**Pull request merged**
