### PR TITLE
Coefficient of Friction

### PR DESCRIPTION
**Pull request by ritika728**
Hey @Srijita-Mandal, I have resolved issue #567 under JWOC. Kindly review

sss

### CODE REVIEW

**Comment by Srijita-Mandal** [comment]
@ritika728 calculator page showing error. Add proper name with extension `.html` and connect files properly.

**Comment by ritika728** [comment]
Yes, can i correct it in my next PR ? Within 10-15 minutes ? @Srijita-Mandal

**Comment by Srijita-Mandal** [comment]
> Yes, can i correct it in my next PR ? Within 10-15 minutes ? @Srijita-Mandal

No. Either commit it in this PR or make a PR for this first. Then the next one.

**Comment by ritika728** [comment]
Okay

**Pull request merged**
