### PR TITLE
Added sum of n numbers

### PR DESCRIPTION
**Pull request by LuckySingh9897**
Screenshot 2023-03-16 005408
Screenshot 2023-03-16 005351
Screenshot 2023-03-16 005335
Screenshot 2023-03-16 005308
Screenshot 2023-03-16 005322

### CODE REVIEW

**Comment by Srijita-Mandal** [comment]
@LuckySingh9897 In the description of the calculator in `index.html`, mention all type of sums that are added. So, that user can reach easily to the calculator by searching.

**Comment by LuckySingh9897** [comment]
Ok @Srijita-Mandal

**Comment by LuckySingh9897** [comment]
Screenshot 2023-03-16 111417

**Comment by LuckySingh9897** [comment]
is it ok @Srijita-Mandal

**Comment by Srijita-Mandal** [comment]
> is it ok @Srijita-Mandal

yes. It is okay

**Comment by LuckySingh9897** [comment]
Or I need to add something else and make the new pr

**Comment by LuckySingh9897** [comment]
@Srijita-Mandal Please add the label .

**Pull request merged**
