### PR TITLE
Added favicon and changed the title of the website.

### LINKED ISSUE #92: Change the title of the website to 'Fix your nums'
@Srijita-Mandal ,
I would like to change the title of the website from ' Home' to ' Fix your nums' .
Please assign me this issue under Jwoc.

### PR DESCRIPTION
**Pull request by Arbtrage**
closes #92 

Added the favicon icon and changed the title of the website from "Home" to "Fix your nums".

image

### CODE REVIEW

**Comment by Srijita-Mandal** [comment]
@Arbtrage Use the favicon that has been already used. 
Use the icon from here - `fix-your-nums/Image/Favicon.png`

**Comment by Arbtrage** [comment]
image

@Srijita-Mandal , done .

**Comment by Srijita-Mandal** [comment]
Merged! 👍

**Comment by Arbtrage** [comment]
Thank you..

**Pull request merged**
