### PR TITLE
Dark Theme Added

### PR DESCRIPTION
**Pull request by Swadhin2001**

### CODE REVIEW

**Comment by Swadhin2001** [comment]
Light Mode :

Screenshot (113)

Dark Mode :

Screenshot (114)

**Comment by Srijita-Mandal** [comment]
@Swadhin2001 Please shift the toggle button to the top right corner of the header.

**Comment by Swadhin2001** [comment]
Fixed

Screenshot (116)


Screenshot (117)

**Comment by Srijita-Mandal** [comment]
@Swadhin2001 Great!! Your PR have been merged. 💯

**Pull request merged**
